export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ADD_NODE = "ADD_NODE"
export const UPDATE_NODE = 'UPDATE_NODE'
export const NODE_CREATION_REQUEST = 'NODE_CREATION_REQUEST'
export const DELETE_NODE = 'DELETE_NODE'